-- 1
-- What are the column names?
-- 2
-- Find the full_names and emails
-- of the transactions listing 20252 as the zip code.
-- 3
-- Use a query to find the names 
-- and emails associated with these transactions.
-- 4
-- Find the ip_addresses and emails listed with these transactions.
-- 5
-- Find the emails in transaction_data with
-- ‘temp_email.com’ as a domain.
-- 6
-- The finance department is looking for a specific transaction. 
-- They know that the transaction occurred from an ip address starting 
-- with ‘120.’ and their full name starts with ‘John’.
-- Can you find the transaction?
-- 7
-- Challenge
-- Return only those customers residing in GA. Use the list of ZIP CODE prefixes
-- (https://en.wikipedia.org/wiki/List_of_ZIP_Code_prefixes)
-- to determine the best query for zip codes belonging to Georgia(GA).